---
abstract: 'Catalyst based application'
author:
  - 'James Smith,,,'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OokOok
no_index:
  directory:
    - inc
    - share
    - t
requires:
  CSS::LESSp: 0
  Catalyst::Action::REST: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Model::Adaptor: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Model::File: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Params::Nested: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::PerUser: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::StatusMessage: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.90012
  Catalyst::View::TT: 0
  Catalyst::View::Thumbnail: 0
  CatalystX::Declare: 0
  CatalystX::RoleApplicator: 0
  Config::General: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  Data::UUID: 0
  Data::Verifier: 0
  DateTime: 0
  ElasticSearch: 0
  Exception::Class: 0
  HTML::FillInForm: 0
  HTML::FormFu: 0
  HTML::FormFu::Model::DBIC: 0
  JSON: 0
  LWP::Protocol::https: 0
  Lingua::EN::Inflect: 0
  Math::Round: 0
  Moose: 0
  MooseX::MarkAsMethods: 0.13
  MooseX::MethodAttributes::Role: 0
  MooseX::NonMoose: 0.16
  MooseX::Singleton: 0.29
  Net::OAuth: 0
  Parse::BBCode: 0
  Set::Scalar: 0
  String::CamelCase: 0
  Text::Markdown: 0
  Text::Textile: 0
  Workflow: 0
  XML::LibXML: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
